language: python
python: 2.7
env:
  global:
    - secure: W5Qhp7ZZcIUusWkyg4ixZX1pmvXMV/m4rxMOY80x3VcxKB7z5mz60ksNuaBRs+GPg9bhJ92vfLhe/bgjj0OO8XA3r9a2HCibMxWih+LlVdd8Iqd/hpuN9OVGCH2odIctSw3YPbuxyyHGagU1pKM+4UGVY0r/g6SJnok6wDEJ+GoKc4jQAgIVRTbXOPsGrNgEo7t5KQix8Wit7l/WqktXTJQ/qUgMKohS8n/3XAVw0F4FUb5903d1r1E1zVa9lnm4hEdRU+YkAr56e/NUhCOgR4FkI19vQ8vLibPERJs6P3aLVLmYRQb304rYwMvecmQWm8rGp1ZQa4YgxyeMAV5QzeSDPZMKar3PIOlmJKxZhDeHQTlVQveinNKEIj4We/K9MH88HcoXW9CJa+Bcw6mTRJiSUXFYzcX1YTJBYUCfFdLKi2Upqy4aJ5An5EiLFig2X1/lSYjc29IFTSeNh55d1ERfc/b4cc5l6cIj62eki3fMtiRXQaK9Okd+jlAEBv3qyL6jIENcQR7tfqId4CCun7DTW1qASo4GLicjrF48o/rsIqdzYd5BxFPh0Mfxc8/Hi9zMDxoWiLS4ltlogl+k8zP1CjKNUD6Ty6XZqWQCRPfgLVhW5rHVu+fRPEPgynrWjVeETCaHPzCqv2Kqdxn1SbEa4+4OKqGuYcrU7IWCmeg=
notifications:
  slack:
    secure: zwNTIebvA+794jgLEKLU9Uy5S+t4mXfCd3rZxOatBc77xTMiRgpf+taK2V62oVig3CeB3ReHZRTAm/cI0PP/ABqRF+ZYOJIZzKkEAnTiQt0NyQQSoBFK3qsUqKDNy805xWuxqeBaIkZ3SK3JFx7VKJAbGXH0D/hhqta9yLGoHCBtiCjYPRDJRs+kpQlq9Y0TDFxGeaUhUMqDwvyQxFnL4oYTLXzTJHlwBLW/MH4Xcn9izw5nvr+3mbR0XTg8d0F1svLsPlvPV3VUSJ/Wdr6ctDkGwzUn1MMxqcJazNlvNDIfesuKb9CKsUZIzWdOhVgTPRtYJc0CyAZ1lSrzJAiLanbHmbdFJCCt08K6A+Mn2rfd14qljVvgrHXjCnVayx1+6Z/mqR3SIwZQapg9DIAmjoXIAmxGgxMndZ6OU191vbu/jKNWOMhpClabyeX80imotqikEULfvmeCVI8NNpQSuz4Pubvl+5gMqXVBRtYTbOEuEPgnOjgt2pW+RkZB/AKFXdK1LsOu6DZD3nyJTjJ9yL+PLGJtjLdFMYcmslVOzSaTApAmx9HFb+ouoFybzBir1fBSBA2OylxAjugovEsbcFNNHhYPSNVDXqZjLiXfxMTY9ysktekvO2F+V/7MNX3BuZdWnNs/MlWtSQN548nDIy9tOwpjJsN5yqF+n75/sBo=
install:
  - pip install GitPython
  - export TRAVIS_COMMIT_MSG="$TRAVIS_REPO_SLUG - $(git log --format=%B --no-merges -n 1)"
script:
  - test "$TRAVIS_PULL_REQUEST" = "false" || travis_terminate 0
  - test "$TRAVIS_BRANCH" = "$TRAVIS_TAG" -o "$TRAVIS_BRANCH" = "master" || travis_terminate 0
  - git config --global user.email 'aussieaddons@aussieaddons.com'
  - git config --global user.name 'Aussie Add-ons Bot'
  - >
    git clone https://github.com/aussieaddons/repo-devel.git $TRAVIS_BUILD_DIR/.deploy-devel &&
    cd $TRAVIS_BUILD_DIR/.deploy-devel &&
    ./manage_repo.py $TRAVIS_BUILD_DIR || travis_terminate 1
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - >
    git add . &&
    git commit --allow-empty -m "$TRAVIS_COMMIT_MSG" &&
    git push || travis_terminate 1
  - if [ -z "$TRAVIS_TAG" ]; then travis_terminate 0; fi
  - >
    git clone https://github.com/aussieaddons/repo.git $TRAVIS_BUILD_DIR/.deploy-prod &&
    cd $TRAVIS_BUILD_DIR/.deploy-prod &&
    ./manage_repo.py $TRAVIS_BUILD_DIR || travis_terminate 1
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - >
    git add . &&
    git commit --allow-empty -m "Update $(basename `git -C $TRAVIS_BUILD_DIR rev-parse --show-toplevel`) to $TRAVIS_TAG" &&
    git push || travis_terminate 1
